apiVersion: v1
kind: Service
metadata:
  name: hello-devops
  labels:
    app: hello-devops
spec:
  type: ClusterIP
  selector:
    app: hello-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
